version: '3.9'

services:
  rustapp:
    container_name: rust-api-crud-template
    image: pad/rust-api-crud-template:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    ports:
      - '${API_PORT}:${API_PORT}'
